<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gameset [
        <!ELEMENT category ( #PCDATA )>
        <!ELEMENT description ( #PCDATA )>
        <!ELEMENT developer_name ( #PCDATA )>
        <!ELEMENT featured_image ( #PCDATA )>
        <!ELEMENT flash_file ( #PCDATA )>
        <!ELEMENT game ( category | description | developer_name | featured_image | flash_file | gameplays | height | id | instructions | launch_date | rating | screenshot | thumbnail | title | url | width )*>
        <!ELEMENT gameplays ( #PCDATA )>
        <!ELEMENT gameset ( game* )>
        <!ELEMENT height ( #PCDATA )>
        <!ELEMENT id ( #PCDATA )>
        <!ELEMENT instructions ( #PCDATA )>
        <!ELEMENT launch_date ( #PCDATA )>
        <!ELEMENT rating ( #PCDATA )>
        <!ELEMENT screenshot ( #PCDATA )>
        <!ELEMENT thumbnail ( #PCDATA )>
        <!ELEMENT title ( #PCDATA )>
        <!ELEMENT url ( #PCDATA )>
        <!ELEMENT width ( #PCDATA )>
        ]>
<gameset>
    <game>
        <id>446</id>
        <title>Sprout</title>
        <thumbnail>http://cdn2.kongcdn.com/game_icons/0000/0637/customlogic.sprout_icon.jpg?10441-op</thumbnail>
        <launch_date>2007-08-01</launch_date>
        <category>Adventure &amp; RPG</category>
        <featured_image>http://cdn2.kongcdn.com/featured_games/0000/0060/sprout_featured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/0446/live/embeddable_446.swf</flash_file>
        <width>640</width>
        <height>480</height>
        <url>http://www.kongregate.com/games/customlogic/sprout</url>
        <description>A storybook adventure staring a tiny seed pod. Journey from your tiny island home to the lush forests of your dreams;  explore the hand-drawn landscape and meet some interesting friends along the way.
        </description>
        <instructions></instructions>
        <developer_name>customlogic</developer_name>
        <gameplays>983014</gameplays>
        <rating>3.87</rating>
    </game>
    <game>
        <id>4041</id>
        <title>N3wton</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/7181/N3wton_120.jpg?3808-op</thumbnail>
        <launch_date>2007-11-05</launch_date>
        <category>Puzzle</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/4041/live/embeddable_4041.swf</flash_file>
        <width>550</width>
        <height>550</height>
        <url>http://www.kongregate.com/games/Zyzic/n3wton</url>
        <description>Maneuver your character through 25 puzzle filled levels.
            Update:  Hopefully I&amp;#8217;ve fixed a few problems with people not getting their badges.  Unfortunately this caused any of your saved games to disappear.  Sorry!
            A hint for level 21:  Read the clue carefully, and pay close attention to the words themselves.  Eventually you&amp;#8217;ll get it ;)
            If you find you can&amp;#8217;t save the game, check to see if you have cookies enabled.  They need to be enabled in order to save the game.
        </description>
        <instructions>Use WASD or the Arrow keys to move your character, click to fire.
        </instructions>
        <developer_name>Zyzic</developer_name>
        <gameplays>626146</gameplays>
        <rating>3.63</rating>
    </game>
    <game>
        <id>1978</id>
        <title>Notessimo</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/3077/Kongregate.png?27244-op</thumbnail>
        <launch_date>2007-08-06</launch_date>
        <category>Music &amp; More</category>
        <screenshot>http://cdn4.kongcdn.com/assets/screenshots/0036/0795/screen3.png</screenshot>
        <flash_file>http://external.kongregate-games.com/gamez/0000/1978/live/embeddable_1978.swf</flash_file>
        <width>586</width>
        <height>530</height>
        <url>http://www.kongregate.com/games/Starburst/notessimo</url>
        <description>Create your own music in this unique flash game that feature a friendly user interface similar to the classic game Mario Paint !
            &amp;nbsp;
            Check out the BETA !
            &amp;nbsp;
            Choose from more than 150 instruments ranging from Guitars, Pianos, Drums and More !
            &amp;nbsp;
            Update : You can now listen to more than 60 songs from Kongregate users !
            &amp;nbsp;
            Please note that you’ll need the Flash 9 plug-in !
            &amp;nbsp;
            If the music lags, you can adjust its quality for slower computer :
            (Settings -&amp;gt; Presets -&amp;gt; Low or Medium).
            &amp;nbsp;
            Post your song ! (File -&amp;gt; Share your Song) in the forum !
        </description>
        <instructions>Choose an instrument and click on the sheet music.
            To produce Flat Note, click while pressing SHIFT and for Sharp Note, click while pressing CTRL.
        </instructions>
        <developer_name>Starburst</developer_name>
        <gameplays>1123538</gameplays>
        <rating>3.95</rating>
    </game>
    <game>
        <id>3197</id>
        <title>Gravitee</title>
        <thumbnail>http://cdn4.kongcdn.com/game_icons/0000/5502/graviteethumb100.png?2680-op</thumbnail>
        <launch_date>2007-09-28</launch_date>
        <category>Sports &amp; Racing</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/3197/live/embeddable_3197.swf</flash_file>
        <width>700</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/FunkyPear/gravitee</url>
        <description>Gravitee is golf in space, using real world Newtonian Physics. A quick tutorial mode will help you learn the basics, but only the most skilled will unlock the 20+ bonuses throughout the ten levels of play.
        </description>
        <instructions>Click and drag ball to strike it. Instructions and tutorial in-game.
        </instructions>
        <developer_name>FunkyPear</developer_name>
        <gameplays>2526845</gameplays>
        <rating>3.92</rating>
    </game>
    <game>
        <id>3595</id>
        <title>Fold</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/6297/fold_icon.png?10213-op</thumbnail>
        <launch_date>2007-10-15</launch_date>
        <category>Action</category>
        <featured_image>http://cdn1.kongcdn.com/featured_games/0000/0095/manifoldfeatured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/3595/live/embeddable_3595.swf</flash_file>
        <width>800</width>
        <height>600</height>
        <url>http://www.kongregate.com/games/joelesler/fold</url>
        <description>Run. Jump. Bend gravity to your will.
            Dizzying heights and insurmountable slopes are no problem with the Gravitational Manifold Anomaly Device.
            This is the full, super-fun-happy version of the game formerly known as Manifold.
        </description>
        <instructions>Arrows or A, W, and D to move. SPACEBAR to retrieve anomalies. Click and hold mouse to aim, drag in direction of desired gravity, then release to fire. R restarts the current level.  P pauses level.  Play Easy episode for detailed instructions.
        </instructions>
        <developer_name>joelesler</developer_name>
        <gameplays>645136</gameplays>
        <rating>3.48</rating>
    </game>
    <game>
        <id>78</id>
        <title>rotaZion</title>
        <thumbnail>http://cdn2.kongcdn.com/game_icons/0000/0115/pixtiz.rotazion_icon.jpg?8217-op</thumbnail>
        <launch_date>2006-12-01</launch_date>
        <category>Action</category>
        <featured_image>http://cdn1.kongcdn.com/featured_games/0000/0010/rotazion_featured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/0078/live/embeddable_78.swf</flash_file>
        <width>350</width>
        <height>350</height>
        <url>http://www.kongregate.com/games/pixtiz/rotazion</url>
        <description>In rotaZion, you play with a bubble bar that you can&amp;#8217;t stop rotating !
            Collect the bubbles and try to avoid the mines !
            Collect the different bonus to protect your bubble bar, makes the mines go slower or destroy all the mines !
            Try to beat 100.000 points ;)
        </description>
        <instructions>Move the bubble bar with the arrow keys !
            Bubble = 500 Points !
            Pixtiz sign = 5000 Points !
        </instructions>
        <developer_name>pixtiz</developer_name>
        <gameplays>411272</gameplays>
        <rating>3.48</rating>
    </game>
    <game>
        <id>2159</id>
        <title>Orb Avoidance 2</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/3437/orb2_logo.png?8996-op</thumbnail>
        <launch_date>2007-08-01</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/2159/live/embeddable_2159.swf</flash_file>
        <width>400</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/Kalinium/orb-avoidance-2</url>
        <description>Orb Avoidance is back, with a new graphical style and more changing gameplay. Mouse avoid to the next level by fighting back against your chasers and smashing them into the blocks.
            Orb Avoidance 2 tries to keep the exciting gameplay of its predecessor, but with an all new graphical design and a new change.
            Blocks can now explode after a certain amount of time, and there are special blocks that will always explode and make more orbs
            Update 2: Added another option, to turn off Orb trails so it&amp;#8217;s much faster to play in the later levels.
            IMPORTANT UPDATE (1): The game has been changed to play more like Orb 1 &amp;#8211; there is now an option to turn exploding blocks off (static balls will still explode). Trippy effects have been increased. It should also be faster laster in the game, as it has been optimized. There are two score statistics, one for exploding, and one without.
            Audio by ParagonX9
        </description>
        <instructions>Use the mouse. Lure the orbs to hit the blocks. Destroying in groups gets more points
        </instructions>
        <developer_name>Kalinium</developer_name>
        <gameplays>66108</gameplays>
        <rating>3.53</rating>
    </game>
    <game>
        <id>1364</id>
        <title>Generic Defense Game</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/1955/kongIcon.png?37245-op</thumbnail>
        <launch_date>2007-06-15</launch_date>
        <category>Shooter</category>
        <featured_image>http://cdn4.kongcdn.com/featured_games/0000/0076/defense.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/1364/live/embeddable_1364.swf</flash_file>
        <width>640</width>
        <height>480</height>
        <url>http://www.kongregate.com/games/PsychoGoldfish/generic-defense-game</url>
        <description>It&amp;#8217;s a survival shooter, a turret defense game, it&amp;#8217;s so generic it&amp;#8217;s unique!
            This bad-boy gives you 8 different games in one, with a ton of options to deliver a unique experience every time you play.
            &amp;#8212;
            Fixed the same-weapon bug and tweeked some settings to make the auto-drones less dominating&amp;#8230; hope that helps balance the fun out.  Some of the games are easier than others, so you may have to try them all to find your niche ;)
            Read more about the game @ http://www.webgamemagazine.com/
        </description>
        <instructions>Use the mouse to aim, WASD to walk around in shooter mode, Q to toggle weapons and E to reload.
            If you find the game easy, or hard there are difficulty settings in the help/options menu.
            If you dislike the control scheme, you can change it in the help/options menu.
        </instructions>
        <developer_name>PsychoGoldfish</developer_name>
        <gameplays>417302</gameplays>
        <rating>3.42</rating>
    </game>
    <game>
        <id>1969</id>
        <title>Speck Oppression</title>
        <thumbnail>http://cdn4.kongcdn.com/game_icons/0000/3059/speck.png?30469-op</thumbnail>
        <launch_date>2007-07-27</launch_date>
        <category>Puzzle</category>
        <featured_image>http://cdn2.kongcdn.com/featured_games/0000/0081/speckop.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/1969/live/embeddable_1969.swf</flash_file>
        <width>550</width>
        <height>400</height>
        <url>http://www.kongregate.com/games/Komix/speck-oppression</url>
        <description>Manipulate gates and teleporters to herd flying sparks into collectors.
        </description>
        <instructions>Use the mouse to drag around various objects. Further instructions are in-game.
        </instructions>
        <developer_name>Komix</developer_name>
        <gameplays>316755</gameplays>
        <rating>3.36</rating>
    </game>
    <game>
        <id>4138</id>
        <title>Ether Cannon</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/7375/KongIcon.jpg?8687-op</thumbnail>
        <launch_date>2007-11-09</launch_date>
        <category>Shooter</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/4138/live/embeddable_4138.swf</flash_file>
        <width>650</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/Kajenx/ether-cannon</url>
        <description>Defend earth from gaseous beasts!  Rage your way through 21 levels of non-stop action!  Be sure to stick around at the end for some cinematic goodies.  Also, there&amp;#8217;s an unlockable Hard Mode if you beat the game.  I finished it, so YES, it is possible!
        </description>
        <instructions>WASD or ARROWS to move.  MOUSE to aim and shoot.  M will mute the sounds, but you&amp;#8217;re crazy if you do. (Yeah, I&amp;#8217;m a DnB fan&amp;#8230;)
        </instructions>
        <developer_name>Kajenx</developer_name>
        <gameplays>254368</gameplays>
        <rating>3.25</rating>
    </game>
    <game>
        <id>256</id>
        <title>Viviparous Dumpling</title>
        <thumbnail>http://cdn4.kongcdn.com/game_icons/0000/0383/Edmund.viviparous-dumpling_icon.jpg?4724-op</thumbnail>
        <launch_date>2007-02-15</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/0256/live/embeddable_256.swf</flash_file>
        <width>666</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/Edmund/viviparous-dumpling</url>
        <description>Maneuver the fetal dumpling with your mouse by grabbing, moving, and throwing him into the nutrient-rich sperm that fills its mothers womb. But be sure to avoid the evil toxoplasm! Four hits from them is all it takes to turn you into fetus soup.
        </description>
        <instructions>Mouse to grab and move. Enter to pause.
        </instructions>
        <developer_name>Edmund</developer_name>
        <gameplays>20416</gameplays>
        <rating>3.11</rating>
    </game>
    <game>
        <id>1682</id>
        <title>Orbular</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/2485/ORBULARS.png?24181-op</thumbnail>
        <launch_date>2007-08-03</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/1682/live/embeddable_1682.swf</flash_file>
        <width>600</width>
        <height>400</height>
        <url>http://www.kongregate.com/games/TastyLamp/orbular</url>
        <description>Use your circular paddle to send the ball flying into the opposing bricks! Smashing the bricks lets you advance the game and spin up a high score.
            Game made by TastyLamp and BDSFlash.
            8/7/07 &amp;#8211; Added Mouse Difficulty, for those who asked for mouse controls.
        </description>
        <instructions>Arrow/WSAD keys or Mouse+Click (in Mouse Difficulty) to move paddle. P to pause game and change quality, mute music or return to menu.
        </instructions>
        <developer_name>TastyLamp</developer_name>
        <gameplays>333626</gameplays>
        <rating>3.09</rating>
    </game>
    <game>
        <id>3624</id>
        <title>Army of Destruction</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/6355/aod_icon_100x75.jpg?5202-op</thumbnail>
        <launch_date>2007-10-17</launch_date>
        <category>Shooter</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/3624/live/embeddable_3624.swf</flash_file>
        <width>750</width>
        <height>350</height>
        <url>http://www.kongregate.com/games/CerebralGames/army-of-destruction</url>
        <description>[NOW WITH MORE LEVELS]
            This is an action shooter where you have to defend your city from the alien invasion.
            The game has 15 intense levels, unique story, 6 unlockable weapons, base upgrades and 6 different enemy units.
            Beat the game and watch the great final.
            UPDATE:
            Based on the community feedback, a lot of people found this game too difficult on the first levels and easy on the last levels. Now we balanced the weapons and enemies to fix this.
            The hit area has been changed a little bit, and the weapons areas and damage has been changed also.
            TIP: Every Enemy has a weapon to defeat it, shotgun and pistol for kamikazes, rifle for bikers and cloack soldiers, rocket and laser for mech units.
            UPDATE 2
            We have added 4 new levels. If you find this game too easy, try this new version for a challenge
            UPDATE 3
            Some people said that mission 10 was way too hard. We&amp;#8217;ve tweaked it a bit to make the mission a little easer
        </description>
        <instructions>Use your mouse to aim, click to shoot, change your weapon with the 1,2,3,4,5 and 6 keys.
            You can use the mouse wheel to faster change of weapon.
        </instructions>
        <developer_name>CerebralGames</developer_name>
        <gameplays>161666</gameplays>
        <rating>3.06</rating>
    </game>
    <game>
        <id>889</id>
        <title>P.O.D.</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/1175/IndieFlashArcade.p-o-d_icon.jpg?4141-op</thumbnail>
        <launch_date>2007-04-19</launch_date>
        <category>Shooter</category>
        <featured_image>http://cdn4.kongcdn.com/featured_games/0000/0069/p-o-d_featured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/0889/live/embeddable_889.swf</flash_file>
        <width>450</width>
        <height>450</height>
        <url>http://www.kongregate.com/games/IndieFlashArcade/p-o-d</url>
        <description>ZOIDS is the new, updated version of Planetary Orbital Defense (P.O.D.). It includes difficulty settings, so if you are having trouble getting the badge, play it on easy mode.
            A new enemy has also been added. Look out for droids!
        </description>
        <instructions>Use the mouse to aim and shoot.
            Features: Customizable key controls ~ Sound options
        </instructions>
        <developer_name>IndieFlashArcade</developer_name>
        <gameplays>174352</gameplays>
        <rating>2.78</rating>
    </game>
    <game>
        <id>2457</id>
        <title>Project Green</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/4031/Untitled-1.jpg?2635-op</thumbnail>
        <launch_date>2007-08-16</launch_date>
        <category>Shooter</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/2457/live/embeddable_2457.swf</flash_file>
        <width>460</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/HStudios/project-green</url>
        <description>Weave through mines and avoid projectiles while making it to the end of each level.
        </description>
        <instructions>Arrows to move, mouse to shoot.
        </instructions>
        <developer_name>HStudios</developer_name>
        <gameplays>13740</gameplays>
        <rating>3.09</rating>
    </game>
    <game>
        <id>1569</id>
        <title>Biff and Baff - Rolling</title>
        <thumbnail>http://cdn2.kongcdn.com/game_icons/0000/2259/bbroll.png?31663-op</thumbnail>
        <launch_date>2007-07-05</launch_date>
        <category>Puzzle</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/1569/live/embeddable_1569.swf</flash_file>
        <width>600</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/Greg76/biff-and-baff-rolling</url>
        <description>Take Biff and Baff on a tour through 6 worlds with 5 levels each. Roll through all the levels. Collecting stars, keys, opening doors and finally rolling to the finish. Can you master it without falling down?
        </description>
        <instructions>Arrows move Biff and Baff. Space to change players.
        </instructions>
        <developer_name>Greg76</developer_name>
        <gameplays>22288</gameplays>
        <rating>3.00</rating>
    </game>
    <game>
        <id>3180</id>
        <title>Ancient Origins{flying fish}</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/5468/ff.jpg?4773-op</thumbnail>
        <launch_date>2007-09-27</launch_date>
        <category>Action</category>
        <featured_image>http://cdn1.kongcdn.com/featured_games/0000/0093/fishfeatured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/3180/live/embeddable_3180.swf</flash_file>
        <width>600</width>
        <height>400</height>
        <url>http://www.kongregate.com/games/mygameline/ancient-origins-flying-fish</url>
        <description>Follow fred on a journey across the sea!
        </description>
        <instructions>fred follows mouse cursor click to jump our of water collect pearls then FLY!!
        </instructions>
        <developer_name>mygameline</developer_name>
        <gameplays>258695</gameplays>
        <rating>2.92</rating>
    </game>
    <game>
        <id>3778</id>
        <title>Breach</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/6660/breach.jpg?2181-op</thumbnail>
        <launch_date>2007-10-24</launch_date>
        <category>Action</category>
        <featured_image>http://cdn2.kongcdn.com/featured_games/0000/0097/breachfeatured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/3778/live/embeddable_3778.swf</flash_file>
        <width>550</width>
        <height>400</height>
        <url>http://www.kongregate.com/games/2DArray/breach</url>
        <description>Oldschool style arcade game, set inside a computer.  Dodge through viruses that are tearing themselves apart to try to destroy you!

            Here are the obstacles for each level (they add up, so level 5 has all of them)

            Level 1: Standard green viral blocks
            Level 2: Indestructible red wall blocks
            Level 3: Random speed changes
            Level 4: Random pauses
            Level 5: Explosive orange hazard blocks

        </description>
        <instructions>Use the mouse to move, and click to shoot.
        </instructions>
        <developer_name>2DArray</developer_name>
        <gameplays>165560</gameplays>
        <rating>2.92</rating>
    </game>
    <game>
        <id>3620</id>
        <title>Headless Havoc</title>
        <thumbnail>http://cdn4.kongcdn.com/game_icons/0000/6347/headlesshavocicon.jpg?3318-op</thumbnail>
        <launch_date>2007-10-16</launch_date>
        <category>Action</category>
        <featured_image>http://cdn1.kongcdn.com/featured_games/0000/0096/hhfeatured.jpg</featured_image>
        <flash_file>http://external.kongregate-games.com/gamez/0000/3620/live/embeddable_3620.swf</flash_file>
        <width>500</width>
        <height>280</height>
        <url>http://www.kongregate.com/games/Void/headless-havoc</url>
        <description>You are the Headless Horseman! Ride through the fields decapitating villagers!
        </description>
        <instructions>Move the mouse to position your horse and click to swing. chop heads and avoid letting villagers get away to keep your havoc bar filled. Try to get more than one villager in a single swing!
        </instructions>
        <developer_name>Void</developer_name>
        <gameplays>56763</gameplays>
        <rating>2.86</rating>
    </game>
    <game>
        <id>782</id>
        <title>Easter Extinction</title>
        <thumbnail>http://cdn4.kongcdn.com/game_icons/0000/1029/atomicnoodle.easter-extinction_icon.png?4311-op</thumbnail>
        <launch_date>2007-04-07</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/0782/live/embeddable_782.swf</flash_file>
        <width>547</width>
        <height>322</height>
        <url>http://www.kongregate.com/games/atomicnoodle/easter-extinction</url>
        <description>Happy Easter everyone!
            This is what happens when Easter try&amp;#8217;s to steal Christmas&amp;#8217;s thunder. The elf&amp;#8217;s go on a killing spree!
            Animation by: Atomic-Noodle
            Programming by: 23450
            Comments:
            Atomic-Noodle:
            THis game took quite a while to make but end the end I&amp;#8217;m pretty happy with it. A lot of the art was done over time so some animation is better than some of the other stuff. Anyway, Enjoy :D
            23450: Biggest game i have ever finished, even though its not even that big. Tells you how many games i finish. : ( Anyway, enjoy!
            P.S. You need a pretty good computer in order to play.
        </description>
        <instructions>Arrow keys to Move
            Control to Change weapon
            Enter to Pause
        </instructions>
        <developer_name>atomicnoodle</developer_name>
        <gameplays>5787</gameplays>
        <rating>2.75</rating>
    </game>
    <game>
        <id>2756</id>
        <title>Shen Long - The Spirit Dragon</title>
        <thumbnail>http://cdn1.kongcdn.com/game_icons/0000/4625/KongIcon.jpg?11981-op</thumbnail>
        <launch_date>2007-08-31</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/2756/live/embeddable_2756.swf</flash_file>
        <width>700</width>
        <height>500</height>
        <url>http://www.kongregate.com/games/Kajenx/shen-long-the-spirit-dragon</url>
        <description>Play as the mystical Chinese dragon of legend and cleanse the dark spirits before they can enter the sacred cherry tree.
        </description>
        <instructions>Defaults to arrow keys, but you can select mouse controls in the pause menu.
        </instructions>
        <developer_name>Kajenx</developer_name>
        <gameplays>23943</gameplays>
        <rating>2.85</rating>
    </game>
    <game>
        <id>5456</id>
        <title>Bobs Revenge</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/9515/kongthumb.jpg?5228-op</thumbnail>
        <launch_date>2007-12-17</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/5456/live/embeddable_5456.swf</flash_file>
        <width>650</width>
        <height>450</height>
        <url>http://www.kongregate.com/games/JFlash/bobs-revenge</url>
        <description>Join Bob in his epic quest to end the Black Knight&amp;#8217;s life!  Is there something bigger going on?
        </description>
        <instructions>Arrows to move/jump/crouch, Z &amp;amp; X to attack, C to backdash
        </instructions>
        <developer_name>JFlash</developer_name>
        <gameplays>33289</gameplays>
        <rating>3.29</rating>
    </game>
    <game>
        <id>5297</id>
        <title>Against the deaD</title>
        <thumbnail>http://cdn3.kongcdn.com/game_icons/0000/9197/kong_ss_high.jpg?9362-op</thumbnail>
        <launch_date>2007-12-16</launch_date>
        <category>Action</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/5297/live/embeddable_5297.swf</flash_file>
        <width>770</width>
        <height>630</height>
        <url>http://www.kongregate.com/games/nobstudio/against-the-dead</url>
        <description>The world is no longer like we used to know &amp;#8230; In this action shooter, Detective Wilson will battle against the dead, pushing forces of evil back to their graves.
            Vampires, zombies and ninjas. Push them back with the weapon you have, as the game progress, you will have the option to upgrade your weapons and buy new ones.
        </description>
        <instructions>Left/Right arrow keys to face in the correct direction, Z X C V to fire, each key corresponds to a different weapon.
        </instructions>
        <developer_name>nobstudio</developer_name>
        <gameplays>6249</gameplays>
        <rating>2.79</rating>
    </game>
    <game>
        <id>5338</id>
        <title>Movement Mayhem</title>
        <thumbnail>http://cdn2.kongcdn.com/game_icons/0000/9279/icon.jpg?10002-op</thumbnail>
        <launch_date>2007-12-13</launch_date>
        <category>Music &amp; More</category>
        <flash_file>http://external.kongregate-games.com/gamez/0000/5338/live/embeddable_5338.swf</flash_file>
        <width>550</width>
        <height>400</height>
        <url>http://www.kongregate.com/games/OriginalSup3rman/movement-mayhem</url>
        <description>UPDATED (Jan 15, 2008){
            -Added new boss levels
            -Changed the movement speed to increase simplicity